version: '3.7'

services:
  app:
    image: modulotechgroup/modulotech-test-rails:dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      URL: http://localhost:3000
      MODULOTECH_TEST_RAILS_DATABASE_HOST: database
      MODULOTECH_TEST_RAILS_DATABASE_NAME: modulotech-test-rails
    stdin_open: true
    tty: true

  database:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modulotech-test-rails
      LC_COLLATE: 'en_US.UTF-8'
      LC_CTYPE: 'en_US.UTF-8'

  redis:
    image: redis:alpine

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  db_data:
